version: "3"
services:
  starsms:
    build:
      context: ./SendText
      dockerfile: Dockerfile
    container_name: StarSMS
    command: node sms.js
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./SendText:/usr/src/app/SendText
      - /usr/src/app/SendText/node_modules

    restart: always

  starapp:
    build:
      context: ./StarDancers
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    container_name: StarApp
    command: npm run dev -- --port 8080 --host
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./StarDancers:/usr/src/app/StarDancers
      - /usr/src/app/StarDancers/node_modules
    restart: always
    networks:
      - proxy

  starapi:
    build:
      context: ./StarDancersAPI
      dockerfile: Dockerfile
    # ports:
    #   - "1337:1337"
    container_name: StarApi
    command: npm run develop
    volumes:
      - ./StarDancersAPI:/usr/src/app/StarDancersAPI
      - /usr/src/app/StarDancersAPI/node_modules
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true